import chroma from "chroma-js";
import loadjs from "loadjs";
import Fuse from "fuse.js";
import Handlebars from "handlebars";
import hljs from "highlight.js";
import introJs from "intro.js";
import iziToast from "izitoast";
import { marked } from "marked";
import moment from "moment";
import pako from "pako";
import Raphael from "raphael";
import socketClusterClient from "socketcluster-client";
import stackinfo from "stackinfo";
import tinysort from "tinysort";
import QRCode from "davidshimjs-qrcodejs";
import colorrick from "./colorrick.cjs";
import MathParser from "./mathparser.js";
import UndoManager from "./undomanager.js";

window.chroma = chroma;
window.ColorRick = colorrick;
window.Fuse = Fuse;
window.Handlebars = Handlebars;
window.hljs = hljs;
window.introJs = introJs;
window.iziToast = iziToast;
window.loadjs = loadjs;
window.marked = marked;
window.MathParser = MathParser;
window.moment = moment;
window.pako = pako;
window.QRCode = QRCode;
window.Raphael = Raphael;
window.socketClusterClient = socketClusterClient;
window.stackinfo = stackinfo;
window.tinysort = tinysort;
window.UndoManager = UndoManager;
