name: 'nightly merge'

on:
  workflow_dispatch:
  schedule:
    - cron:  '20 3 * * *'

jobs:
  nightly-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: nightly merge
        uses: usertesting/gh-action-nightly-merge@ut-v1.3.1-fixed
        with:
          stable_branch: 'develop'
          development_branch: 'nightly'
          allow_ff: false
          allow_forks: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
